### ISSUE TITLE
Electron-download NPM dependency failed to download electron version

### ISSUE THREAD

**Issue by kevinlacire** [C-JSN/D3-ID3#85]
Hi,

On Ubuntu 16.04 I can't entirely install ID3 due to this following error :

```bash
npm install

> electron@https://registry.npmjs.org/electron/-/electron-1.6.8.tgz postinstall /home/USERNAME/Bureau/D3-ID3/node_modules/electron
> node install.js

/home/USERNAME/Bureau/D3-ID3/node_modules/electron/install.js:47
  throw err
  ^

Error: Failed to find Electron vhttps://registry.npmjs.org/electron/ for linux-x64 at https://github.com/electron/electron/releases/download/vhttps://registry.npmjs.org/electron//electron-vhttps://registry.npmjs.org/electron/-linux-x64.zip
    at Request.<anonymous> (/home/USERNAME/Bureau/D3-ID3/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestResponse (/home/USERNAME/Bureau/D3-ID3/node_modules/request/request.js:1074:10)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:564:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:453:20)
    at emitOne (events.js:115:13)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.1.tgz (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.1.tgz: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@https://registry.npmjs.org/electron/-/electron-1.6.8.tgz postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@https://registry.npmjs.org/electron/-/electron-1.6.8.tgz postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-06T13_33_23_740Z-debug.log
```
I seems that the electron version passed to the electron-download NPM dependency is replaced by a URL :

https<span><span>://github.com/electron/electron/releases/download/v_**https<span></span>://registry.npmjs.org/electron//electron-vhttps<span></span>://registry.npmjs.org/electron/**_-linux-x64.zip

**Comment by PiN73** [comment]
Exactly the same problem, solved by `npm install electron` before `npm install`
